### ISSUE TITLE
Show instance derivation of GADT defined in companion object 

### ISSUE THREAD

**Issue by coutoPL** [typelevel/kittens#209]
I have a problem with Show instance derivation of GADT defined in companion object. 
Here is the example:

```
scala 2.13.1 // but I think, I see the same issue on scala 2.12.8
kittens 2.0.0
```

```scala
object example {

  import cats.Show
  import cats.derived.semi
  import cats.implicits._

  sealed trait Response
  object Response {

    final case class OK(message: String) extends Response
    final case class Failure(message: String, error: Error[Int]) extends Response

    sealed trait Error[T]
    object Error {
      final case class Recoverable(cause: Int) extends Error[Int]
      case object Unexpected extends Error[Unit]
    }
  }

  implicit val show: Show[Response] = {
    semi.show
  }
}
```

ends up with compilation error:
```
Error:(21, 10) diverging implicit expansion for type cats.derived.util.VersionSpecific.Lazy[cats.derived.MkShow[A]]
starting with method catsKernelStdHashForSortedMap in trait SortedMapInstances
    semi.show
```

The workaround is pretty simple - I have to move `Error` definition outside of `Response` companion object:

```scala
object example {

  import cats.Show
  import cats.derived.semi
  import cats.implicits._

  sealed trait Response
  object Response {

    final case class OK(message: String) extends Response
    final case class Failure(message: String, error: Error[Int]) extends Response
  }

  sealed trait Error[T]
  object Error {
    final case class Recoverable(cause: Int) extends Error[Int]
    case object Unexpected extends Error[Unit]
  }

  implicit val show: Show[Response] = {
    semi.show
  }
}
```

Now it compiles. 
Also there is no issue when `Error` is not GADT or have no generic type.

But still, looks like a bug. I'm not pretty sure if this applies to kittens or shapeless, but I think you have now enough info to figure it out ;)

Cheers. Great lib guys.

**Comment by joroKr21** [comment]
That's really weird

**Comment by joroKr21** [comment]
Also we can notice that the implicit error message regressed (in 2.12 shapeless' `Lazy` can forward to the original `implicitNotFound` message because it's implemented with a macro, but this doesn't work in 2.13).

**Comment by joroKr21** [comment]
See scala/scala#8596 for the error message

**Comment by joroKr21** [comment]
That's not a kittens problem. It's due to the use of `shapeless.Typeable`
(to get the case class name and type parameters):

```scala
scala> import shapeless._


scala> :paste
// Entering paste mode (ctrl-D to finish)

  sealed trait Response
  object Response {
    final case class OK(message: String) extends Response
    final case class Failure(message: String, error: Error[Int]) extends Response

    sealed trait Error[T]
    object Error {
      final case class Recoverable(cause: Int) extends Error[Int]
      case object Unexpected extends Error[Unit]
    }
  }

  Typeable[Response.Failure]

// Exiting paste mode, now interpreting.

         Typeable[Response.Failure]
                 ^
On line 13: error: No default Typeable for parametrized type Response.Error[Int]
```

**Comment by joroKr21** [comment]
The problem with shapeless is that we are missing `Typeable` derivation for sealed traits.
This is planned for shapeless 2.4.0. I will close this because there's nothing more we can do.
